# -*- coding: utf-8 -*-
"""data_analysis_sample.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHlRn9JPmJFbq6Db3s_CQfBNWeb8bOQd
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Sales': [1200, 1500, 1700, 1600, 1800, 2100]
}

df = pd.DataFrame(data)

print("📊 Sales Data:")
print(df)

mean_sales = df['Sales'].mean()
max_sales = df['Sales'].max()
min_sales = df['Sales'].min()

print("\n📈 Sales Statistics:")
print(f"Average sales: {mean_sales}")
print(f"Highest sales: {max_sales}")
print(f"Lowest sales: {min_sales}")
print("\n")

plt.figure(figsize=(8,5))
sns.barplot(x='Month', y='Sales', hue='Month', data=df, palette='viridis', dodge=False, legend=False)
plt.title('Monthly Sales Chart')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.tight_layout()
plt.subplots_adjust(top=0.9, bottom=0.1, left=0.1, right=0.95, hspace=0.3)
plt.savefig('monthly_sales.png')
plt.show()
